# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a846679c25c5d755c067c7f42fc802790593cc230bbd7afe5fa323c845bc500463d30fb86269b34cee1812f347ae42e34d77995ac5556d0c50b9042b81a330

test:
  secret_key_base: d1eeb4c87486609953a71196c004dc3394f0a95349abcf5662fc37ad656ee0ef496d9d8ed079badf1c9902d4d0b5ace15668d34c7218dd682d10e332736c4be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
